version: 1

run:
  timeout: 5m
  tests: true

linters-settings:
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/eyeskiller/fail2ban-notifier
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  depguard:
    list-type: allowlist
    include-go-root: true
    packages-with-error-message:
      - github.com/sirupsen/logrus: "logging is allowed only by standard library"
    allow-list:
      main:
        - github.com/eyeskiller/fail2ban-notifier/internal
        - github.com/eyeskiller/fail2ban-notifier/pkg
        - github.com/eyeskiller/fail2ban-notifier/cmd
        - github.com
        - context
        - bytes
        - encoding
        - errors
        - flag
        - fmt
        - io
        - log
        - net
        - net/http
        - os
        - os/exec
        - path
        - path/filepath
        - runtime
        - strings
        - sync
        - time

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive        # replaces golint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused        # replaces varcheck, structcheck, deadcode
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
